version: '2.1'

services:
  thedevbranch:
    image: thedevbranch
    build: .
    environment:
      PUBLICWEB: ./publicweb
    ports:
      - 4200:3000
      - 9229:9229
    command: node --inspect index.js